# coding: utf-8
# 常量
language_item = {
    'language': '语言',
    'chinese': '中文',
    'traditional chinese': '繁体中文',
    'english': '英语',
    'arabic': '阿拉伯语',
    'armenian': '亚美尼亚语',
    'azerbaijani': '阿塞拜疆语',
    'bengali': '孟加拉语',
    'dutch': '荷兰语',
    'french': '法语',
    'georgian': '格鲁吉亚语',
    'german': '德语',
    'greek': '希腊语',
    'hindi': '北印度语',
    'indonesian': '印度尼西亚语',
    'italian': '意大利语',
    'japanese': '日语',
    'korean': '韩语',
    'malaysian': '马来西亚语',
    'pashto': '普什图语',
    'polish': '波兰语',
    'portuguese': '葡萄牙语',
    'russian': '俄语',
    'serbian': '塞尔维亚语',
    'spanish': '西班牙语',
    'telugu': '泰卢固语',
    'thai': '泰语',
    'turkish': '土耳其语',
    'ukrainian': '乌克兰语',
    'urdu': '乌尔都语',
    'vietnamese': '越南语',
}
